### ISSUE TITLE
Question about base BIDAF model and paper results. 

### ISSUE THREAD

**Issue by RachelKer** [davidgolub/QuestionGeneration#10]
Hello,   I am trying to reproduce your results on your paper. I did not get the same results as you with a BIDAF model (GitHub.com/allenai/bi-att-flow) trained on SQuAD v1 only and tested on newsqa. I used a pretrained BIDAF model. With 24EM and 39 F1 score, you get some 5 points higher results than I have. 

What exact model did you use ? In your git, you train a model on SQuAD and « an old dataset ». Which dataset is it ?

 I thank you for any hindsight you might have on this.

**Comment by davidgolub** [comment]
Hi Rachel,
Thanks for your comment. The model I used should be in the repository. If that doesn’t work, it was the BiDAF model in tensorflow before it was converted to pytorch

**Comment by RachelKer** [comment]
Thank you for your answer. What is the difference between the news_qa unsupervised datasets ? (unsupervised, unsupervised_old and unsupervised_large). Are they different methods of Question Generation or Answer Generation ?

Thanks again, 

Rachel
